Positive	Negative	Text
3	-3	The latest AuthLib breaks Oauth, returns the "Error returning OAuth user info: missing_token".Downgrading back to authlib==0.15.5 fixes this error and allows SSO to work again.#### How to reproduce the bug1. Setup Google Oauth2. Install Authlib 1.0.03. Try to login4. See Error returning OAuth user info: missing_token### Expected resultsLogin via google SSO keeps working.### Actual resultsLatest AuthLib releases throws a missing_token error.#### ScreenshotsIf applicable, add screenshots to help explain your problem.![image](https://user-images.githubusercontent.com/10971263/159022342-2223774a-8881-4ec2-bc0f-fb46a7e341ed.png)### Environment(please complete the following information):- browser type and version: Chrome- superset version: `1.4.0` - python version: `3.9.7`- node.js version: `16.9.0`- any feature flags active:### ChecklistMake sure to follow these steps before submitting your issue - thank you!- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.- [x] I have reproduced the issue with at least the latest released version of superset.- [x] I have checked the issue tracker for the same issue and I haven't found one similar.### Additional contextAdd any other context about the problem here.
1	-1	Is this still an issue on 2.0.1?
1	-1	I have tested this again. It does not seem to be an issue anymore. Just note that it does not work if using:`          'server_metadata_url': 'https://accounts.google.com/.well-known/openid-configuration',`The URLs have to be manually defined.
3	-1	Thanks @longtomjr!
